### PR TITLE
Added the ability to pass and receive arguments

### PR DESCRIPTION
**Pull request by ianko**
Solves #46, #78 and #93.

### CODE REVIEW

**Comment by bluemix** [comment]
@KevinTheGray I hope to merge this feature

**Comment by lukef** [comment]
I will be reviewing it but I'm not sure this will make a release before 2.0 (where the feature is already built using a different approach). This is a breaking change and I'm not really willing to roll a 2.0 just for this.

**Comment by bluemix** [comment]
Ok, thanks for your reply.
is there any date when 2.0 will be released?

**Comment by Kunoacc** [comment]
> Ok, thanks for your reply.
> is there any date when 2.0 will be released?


+1

**Comment by rchavik** [comment]
> I will be reviewing it but I'm not sure this will make a release before 2.0 (where the feature is already built using a different approach). This is a breaking change and I'm not really willing to roll a 2.0 just for this.

Is there a branch for 2.0?  I can only find `routable` which is for something else afaik

**Comment by WingCH** [comment]
I hope to merge this feature

**Comment by softmarshmallow** [comment]
this seems quite critical, https://github.com/Flutterando/modular supports arguments pass.

**Comment by lukepighetti** [comment]
Hi! Thanks for the contribution. I took your idea and added custom RouteSettings to the latest release, so I'm closing this. Cheers!

**Comment by softmarshmallow** [comment]
@lukepighetti Hm... you should have take more concern here. @ianko poured some hard work here. You could have simply just care more. It's been around more than a year

**Comment by lukepighetti** [comment]
> @lukepighetti Hm... you should have take more concern here. @ianko poured some hard work here. You could have simply just care more. It's been around more than a year

Unfortunately I triaged the issues before the PRs, and in doing so I had already implemented RouteSettings based arguments by the time I triaged this. There is no doubt that a lot of care was put in this PR but it just didn't work out. Thanks for the thoughtful message.

**Comment by ianko** [comment]
@softmarshmallow thanks for the consideration. 

I am fine with the solution. I am glad the feature is now available, it doesn't matter in which way.

I am even happier to see this project moving once again and with plans for the 2.0.

You can count on me @lukepighetti.

**Pull request closed without merging**
