### PR TITLE
Add dynamic object 

### PR DESCRIPTION
**Pull request by marscj**
Maybe you need an object, not just a List<String>, like this:

AppRouter.instance.navigateTo(context, '/useProfile', objcet: {'user': firebaseUser});

.....

Handler profileHandler = new Handler(
  handlerFunc: (BuildContext context, Map<String, List<String>> params, [dynamic object]) {
    return new ProfilePage(object['user']);
  });

...

class ProfilePage ... is view
.... 
if you need
pressed() => user.sendEmailVerification()

If you just pass the List<String>, you can't do this.

### CODE REVIEW

**Comment by gabdsg** [comment]
Status?

**Comment by lukepighetti** [comment]
Hi! Thanks for the contribution. I took your idea and added custom RouteSettings to the latest release, so I'm closing this. Cheers!

**Comment by gabdsg** [comment]
@lukepighetti  How do you get the RouteSettings in the handlerFunc?

**Comment by lukepighetti** [comment]
Hang on, I'm going to revisit this. I think we can do better.

**Comment by lukepighetti** [comment]
Yeah, I looked over it and for the current status of Fluro the best option is going to be to use the context inside the route handler to pull the settings. I've added an extension in https://github.com/lukepighetti/fluro/commit/c84ed03c5f49705d8d716763dd578c0e5a9e27df that will give you a simple way to handle this.

```dart
var rootHandler = Handler(
    handlerFunc: (BuildContext context, Map<String, List<String>> params) {
  /// Get [RouteSettings]
  print(context.settings);

  /// Get [RouteSettings.arguments]
  print(context.arguments);

  return HomeComponent();
});
```

**Pull request closed without merging**
