### PR TITLE
renamed class to be unambiguous

### PR DESCRIPTION
**Pull request by falkorichter**
fixes https://github.com/theyakka/fluro/issues/173

### CODE REVIEW

**Comment by SvenSchoene** [comment]
This repository might be dead -- which is a shame, because Fluro is quite good and the author has done a great job with this.

I also opened two PRs on this repo over a year ago and nothing has happened. I since forked this for my own needs.

In any case, thanks for this fix, I just ran into this issue myself after updating Flutter. Thumbs up! 👍

**Comment by vinurs** [comment]
is there any other alternative route library?

**Comment by SvenSchoene** [comment]
Quite a few: https://pub.dev/packages?q=router  

I haven't tried any of them personally, though.

**Comment by lukepighetti** [comment]
Hi! Thanks for your contribution. I am closing this because this feature has been added manually in the latest release.

**Pull request closed without merging**
