### PR TITLE
Add parameter "opaque" for support transparent background

### PR DESCRIPTION
**Pull request by alen256**

### CODE REVIEW

**Review by developerpaaji — COMMENTED** [review]
Looks good. @lukepighetti can u merge this

**Comment by lukepighetti** [comment]
Can someone give me an explanation of the use case here? Photos would be helpful

**Comment by lukepighetti** [comment]
Oh wow, automerge didn't work. My bad.

**Comment by lukepighetti** [comment]
Closed by https://github.com/lukepighetti/fluro/pull/257, thank you

**Pull request closed without merging**
